### ISSUE TITLE
pkg_resources imported but setuptools not listed as dependency

### ISSUE THREAD

**Issue by tlambert03** [fsspec/dropboxdrivefs#16]
found by running the example

```python
File ~/dev/self/slydb/.venv/lib/python3.12/site-packages/dropbox/session.py:1
----> 1 import pkg_resources
      2 import os
      3 import ssl

ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by MarineChap** [comment]
Hello, thanks for reporting it. Is it fixed with the latest release ? I move to the pyproject.toml way to package and setuptools is marked as required. 
Thanks

**Comment by tlambert03** [comment]
well, it's sort of and sort of not fixed :joy:
I'm still able to reproduce it...

however, I apologize, I didn't look closely enough at my stack trace above... this issue was actually a *dropbox* issue (not your issue), and they fixed it in https://github.com/dropbox/dropbox-sdk-python/pull/489 ... which was released in dropbox v12 on may 14th. 

However, for some strange reason, when I install `dropboxdrivefs`, it pulls down dropbox 11.36.2:

```bash
$ uv pip install dropboxdrivefs
Resolved 11 packages in 75ms
Installed 11 packages in 13ms
 + certifi==2024.2.2
 + charset-normalizer==3.3.2
 + dropbox==11.36.2
 + dropboxdrivefs==1.4.0
 + fsspec==2024.5.0
 + idna==3.7
 + ply==3.11
 + requests==2.32.0
 + six==1.16.0
 + stone==3.3.6
 + urllib3==2.2.1
```

whereas if I directly install all of your dependencies, it pulls down v12 (which works)

```bash
$ uv pip install fsspec dropbox requests
Resolved 10 packages in 3ms
Installed 10 packages in 11ms
 + certifi==2024.2.2
 + charset-normalizer==3.3.2
 + dropbox==12.0.0
 + fsspec==2024.5.0
 + idna==3.7
 + ply==3.11
 + requests==2.29.0
 + six==1.16.0
 + stone==3.3.1
 + urllib3==1.26.18
```

in any case, since you're not hard-pinning any of your dependencies, and since this is fixed upstream (last week) in dropbox, it's safe to say this is not your issue anymore :) and whatever weirdness I'm seeing with pip install (using uv fwiw), will likely resolve itself soon.  thanks!
